[package]
name = "proto"
version = "0.1.0"
edition = "2021"
publish = false
build = "build.rs"

[dependencies]
prost = { workspace = true }
prost-types = { workspace = true }
tonic = { workspace = true }

[build-dependencies]
protoc-bin-vendored = "3.1"
tonic-build = { workspace = true }
